const DEFAULT_COMMAND = {
    hrs: false,
    pts: true,
    timeField: '',
    auto: true,
    stopField: 45400,
    drink10: 0,
    drink20: 0,
    drink30: 0,
    date: false,
    plvl: 83,
    jewels: false,
    tokens: 910,
    pexp: 236,
    bonus2: false,
    bonus1: true,
    eventpts: 28211,
    difSelect: 'pro/15',
    grade1s: true,
    grade1a: false,
    grade1b: false,
    grade1c: false,
    multi11: true,
    multi12: false,
    grade2s: false,
    grade2a: false,
    grade2b: true,
    grade2c: false,
    multi21: false,
    multi22: true,
    multi24: false,
    eventdif3: false,
    eventdif3: false,
    effField: 0.8,
    eventdif0: false,
    eventdif1: false,
    eventdif2: true,
}

module.exports = {
    DEFAULT_COMMAND
}